export const FETCH_CURRENCY = 'FETCH_CURRENCY';
export const CHANGE_FROM_INPUT = 'CHANGE_FROM_INPUT';
export const CHANGE_TO_INPUT = 'CHANGE_TO_INPUT';
export const CHANGE_FROM_CURRENCY = 'CHANGE_FROM_CURRENCY';
export const CHANGE_TO_CURRENCY = 'CHANGE_TO_CURRENCY';
export const HANDLE_ERROR = 'HANDLE_ERROR';
export const SWITCH_BETWEEN = 'SWITCH_BETWEEN';